export * from "./Home";
export * from "./Dashboard";
export * from "./Graph";
export * from "./Compare";
export * from "./Profile";
export * from "./Evidence";
export * from "./DevPlan";
export * from "./Admin";
export * from "./Login";
export * from "./CompetencyDetail";
export { Dashboard } from "./Dashboard";
export { Graph } from "./Graph";
export { Compare } from "./Compare";
export { Profile } from "./Profile";
export { Evidence } from "./Evidence";
export { DevPlan } from "./DevPlan";
export { Admin } from "./Admin";
export { Login } from "./Login";
export { CompetencyDetail } from "./CompetencyDetail";
